### ISSUE TITLE
Implement Notification selectors

### ISSUE THREAD

**Issue by ornew** [ornew/tekton-integration#3]
Compare to see if it matches the definition
https://github.com/ornew/tekton-integration/blob/da5bab10b0c0809e39f34a28a86d8b4aabc0216a/pkg/controllers/pipelinerun_controller.go#L107

```yaml
  filter:
    taskRun:
      enabled: false
    pipelineRun:
      enabled: true
    namespaceSelector:
      matchNames:
        - *
    labelSelector:
      matchLabels:
        foo: bar
      matchExpressions:
        - key: env
          operator: In
          values: [dev]
```
