### ISSUE TITLE
Always validate notifications

### ISSUE THREAD

**Issue by ornew** [ornew/tekton-integration#4]
- As-is: Only when the status changes
- To-be: Always

However, it is necessary to add an option to CRD to notify only when the status changes. In most cases, you only need to be notified when your status changes.

https://github.com/ornew/tekton-integration/blob/da5bab10b0c0809e39f34a28a86d8b4aabc0216a/pkg/controllers/pipelinerun_controller.go#L68-L72

Maybe like this:

```yaml
apiVersion: integrations.tekton.dev/v1alpha1
kind: Notification
metadata:
  name: slack-notification
spec:
  when: StatusChanged # or Always, ...
  providerRef:
    name: slack-app
```
